apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wp-db
  name: wp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp-db
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          resources: {}
status: {}
