apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wp-app
  name: wp-app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: wp-app
status:
  loadBalancer: {}
