apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_DATABASE
          value: "exampledb"
        - name: MYSQL_USER
          value: "exampleuser"
        - name: MYSQL_PASSWORD
          value: "examplepass"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "1"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "1"
